config/routes.rb
Rails.application.routes.draw do

  resources :articles
  root 'pages#home'
  
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', :to => 'sessions#new'
  post 'login', :to => 'sessions#create'
  delete 'logout', :to => 'sessions#destroy'
  
  resources :users, :except => [:new]
  
  resources :categories, :except => [:destroy]
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description , presence: true, length: { minimum: 10, maximum: 500}
  validates :user_id, presence: true 
  
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name , :presence => true, :uniqueness => true, :length => {:minimum => 5, :maximum => 25}
  has_many :article_categories
  has_many :articles , through: :article_categories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, :dependent => :destroy
  validates :username, presence: true, 
  uniqueness: {case_sensative: false},
  length: {minimum: 3, maximum: 25}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i 
  
  validates :email, 
  uniqueness: {case_sensative: false},
  format: { with: VALID_EMAIL_REGEX }
  
  
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You have to be logged in to perform this action!!"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article , only: [:edit,:update,:show,:destroy]
  before_action :require_user , :except => [:index, :show]
  before_action :require_same_user, :only => [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  
  def destroy
    
    @article.destroy();
    flash[:danger] = "Article deleted successfully!!"
    redirect_to articles_path
  end
  
  def create
    
    @article = Article.new(article_params)
    
    @article.user = current_user
    if @article.save
      flash[:success] = "article created successfully!!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
    
  end
  
  def update
    
    if @article.update(article_params)
      flash[:success] = "Article updated successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
      
  end
  
  
  def show
    
  end
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  
  private
  def article_params
    params.require(:article).permit(:title, :description,:category_ids => [])
  end
  
  
    def require_same_user
     if current_user != @article.user && !current_user.admin?
       
       flash[:danger] = "You do not have permisson to edit or delete others article"
       redirect_to root_path
     end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_admin, :except => [:index,:show]
  before_action :set_category , only: [:edit,:update,:show,:destroy]
  
  def index
    @categories = Category.paginate(:page => params[:page], :per_page => 5)
  end
  
  def new
    @category = Category.new
  end
  
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(:page => params[:page], :per_page => 5)
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successgully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def edit
   
    
  end
  
  
  def update
    
    if @category.update(category_params)
      flash[:success] = "Category Updated Successfully"
      redirect_to edit_category_path(@category)
    else
      redirect_to root_path
    end
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if(!logged_in? || (logged_in? && !current_user.admin?))
      flash[:danger] = "only admin can perform this action"
      redirect_to categories_path
    end
  end
  
  def set_category
     @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
    
  end
  
  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  def create
     user = User.find_by_email(params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       session[:username] = user.username
       flash[:success] = "user logged in successfully"
       redirect_to user_path(user)
     else
       flash.now[:danger] = "Please provide valid login information!!!"
       render 'new'
     end
    
  end
  def destroy 
    session[:user_id] = nil
    flash[:success] = "user logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  # before_action :set_user, :only => [:edit,:update,:show]
  
  before_action :require_user, :except => [:index, :create, :new]
  before_action :admin_only, :only => [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page:5 )
  end
  
  def new
    @user = User.new
  end
  
  
  def destroy
    @user = User.find(params[:id])
    
    @user.destroy
    flash[:danger] = "User deleted successfully"
    redirect_to users_path
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Wellcome to Alpha Blog #{@user.username}"
      
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
       flash[:success] = "User updated successfully"
       redirect_to articles_path
     else
       render 'edit'
     end
  end
  
  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(:page => params[:page], :per_page => 1)
  end
  
  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
  
  def admin_only
    if !logged_in? || !current_user.admin?
      flash[:danger] = "Only admin can perform this operation!!"
      redirect_to root_path
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username,class: "img-circle")
    
  end
end

app/views/articles/_articles.html.erb
<% obj.each do |article|%>
<div class="row">
<div class = "col-md-8 col-md-offset-2">
  <div class = "well well-lg">
  
    <article>
      <div class = "article-title">
        <%= article.title %>
      </div>
      <hr>
      <div class = "article-body">
        <%= article.description %><br>
        <hr>
        <small>Created By <%= article.user.username if article.user %> ,
        <%= time_ago_in_words(article.created_at)%> ago</small>
      </div>
      <hr>
      <div class = "action-style">
        <%= link_to  "Read More..", show=article_path(article.id),class: "btn btn-info btn-xs" %>
        <%if article.categories.any? %>
         <p>Categories <%= render article.categories %></p>
        <%end%>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <%= link_to  "Edit Article", edit_article_path(article.id),class: "btn btn-success btn-xs" %>
          <%= link_to "Delete" ,article_path(article.id) ,class: "btn btn-danger btn-xs", method: :delete , data: {confirm: "are you sure?"}%>
        <% end %>
      </div>
    </article>
  </div>
</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render "/layouts/errormessage", obj: @article %>





<div class = "row">
  <div class = "col-md-12">
    
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :title  %>
        </div>
        <div class = "col-md-8">
          <%= f.text_field :title , class: "form-control", autofocus: true %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :description %></br>
        </div>
        <div class = "col-md-8">
          <%= f.text_area :description , class: "form-control" , rows: 10 %>
        </div>
      </div>
      <div class = "col-md-offset-2 col-md-8">
        <div class = "row">
          
          <%= f.collection_check_boxes(:category_ids,Category.all, :id, :name) do |cb| %>
            <%= cb.label(:class => "check-box"){cb.check_box(:class => "check_box")} + cb.text %>
          <% end %>
          
        </div>
      </div>
      <div class = "col-md-offset-2 col-md-2">
        <%= f.submit class: "btn btn-success" %>
      </div>
      
    <% end %>
    <div class="col-md-2 ">
      <%= link_to "Go for Articles List", articles_path ,class: "btn btn-info" %>
    </div>
  </div>
</div>


  

app/views/articles/edit.html.erb
<h2>Edit existing article</h2>

<%= render 'form'%>
  

app/views/articles/index.html.erb
<h1 align = "center">Listing all articles</h1>
<div align="center">
  <%= will_paginate %>
</div>

<%= render 'articles', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<center><h1>Create New Page</h1></center>


<%= render 'form'%>

app/views/articles/show.html.erb
<h2 align = "center">
    <%= @article.title %>
  </h2>
  <div class = "well">
    <ul class = "listing">
    <div class = "row" align ="center">
      
      <div class = " col-md-4 col-md-offset-4">
        <li><%= gravatar_for(@article.user,150) %></li>
        <li><%= link_to @article.user.username, user_path(@article.user) %></li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
      
    </div>
    </ul>
    
    <article>
        <%= @article.description %>
        <% if @article.categories.any? %>
          <p>Categories : <%= render @article.categories %> </p>
        <% end %>
    </article>
  <hr>
  <div class = "row action-style">
      <strong><%= link_to "Article List", articles_path,class: "btn btn-info btn-xs" %><strong>
      <% if logged_in? && @article.user == current_user %>
        <strong><%= link_to  "Edit Article", edit_article_path(@article.id),class: "btn btn-success btn-xs" %></strong>
        <strong><%= link_to "Delete" ,article_path(@article.id) ,class: "btn btn-danger btn-xs", method: :delete , data: {confirm: "are you sure?"}%></strong>
      <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class = "badge">
  <%= link_to(category.name,category_path(category))%> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render "/layouts/errormessage", obj: @category %>
<div class = "row"> </div> 
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :name  %>
        </div>
        <div class = "col-md-8">
          <%= f.text_field :name , class: "form-control", autofocus: true %>
        </div>
      </div>
      
      <div class = "col-md-offset-2 col-md-2">
        <%= f.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

app/views/categories/edit.html.erb
<h2>Edit Article</h2>

<%= render "form" %>

app/views/categories/index.html.erb
<h2 align = "center">Categories List</h2>
<div align = "center">
  <%= will_paginate %>
  <div class = "row">
    <ul class = "listing">
     <% @categories.each do |category| %>
     <div class="well col-md-4 col-md-offset-4">
        <li class = "article-title" >
          <%= link_to category.name , category_path(category) %>
        </li>
        <li><%= link_to pluralize(category.articles.count,"article") , category_path(category) %></li>
      </div>
      <% end %>
    </ul>
   
   
  </div>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<center><h1>Create New Category</h1></center>


<%= render "form" %>





   

app/views/categories/show.html.erb
<h1 align = "center"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class = "row" align = "center">
    <span class = "badge"><%= link_to "Edit Category", edit_category_path(@category) %></div>
  </div>
  <br/>
<%end %>
<div align="center">
  <%= will_paginate(@category_articles) %>
</div>

<%= render 'articles/articles', obj: @category_articles %>

<div align="center">
  <%= will_paginate(@category_articles) %>
</div>

app/views/layouts/_errormessage.html.erb
<% if obj.errors.any? %>
<div class = "row">
  <div class = "col-md-8 col-md-offset-2">
    <div class = "panel panel-danger">
      <div class = "panel-heading">
        <div class = "panel-title">
        Could not save due to <%= pluralize(obj.errors.count,"error") %>
        </div>
      </div>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |message| %>
          <li  ><%=message %></li>
          <% end %>
        </ul>
          
        
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class = "container">
  <footer class = "footer" >
    <small>
      Copyright &copy <a href = "newaz.sharif@hotmail.com">Newaz Sharif</a>
    </small>
    <p>Hope I will be a great rails developer</p>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class = "row">
 <div class = 'col-md-10 col-md-offset-1'> 
  <% flash.each do |name,msg|%>
  
    <div class = "alert alert-<%=name%>">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </div>
  
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">Alpha Blog</a>-->
      <%= link_to "Idea Blog",root_path,  class: "navbar-brand",id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li ><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
             
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
              
        <% end %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
             
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |c| %>
            <li><%= link_to c.name, category_path(c) %></li>
            <% end %>
            <% if logged_in? && current_user.admin? %>
            <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>

        <li><%= link_to "Users" , users_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "logout", logout_path, :method => :delete%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_for(current_user,25) %>  <%= current_user.username%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit information" ,edit_user_path(current_user.id)%></li>
              <li><%= link_to "Show Profile" ,user_path(current_user.id)%></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path%></li>
          <li><%= link_to "Signup", signup_path %></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Idea Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/navigation' %>
  <%= render '/layouts/messages' %>

<div class="container">
  <%= yield %>
  
</body>
<footer>
<%= render '/layouts/footer' %>

</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Home</title>
</head>

<body>
  <h2>This is About page</h2>
  <%= link_to 'Home', pages_home_path %>
</body>

</html>

app/views/pages/home.html.erb
<div class = "jumbotron center">
  <h1>Idea-Blog</h1>
  <%= link_to "Sign Up", signup_path, class: "btn btn-danger btn-lg" %>
</div>

app/views/users/_form.html.erb
<%= render "/layouts/errormessage", obj: @user %>





<div class = "row">
  <div class = "col-md-12">
    
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :username  %>
        </div>
        <div class = "col-md-8">
          <%= f.text_field :username , class: "form-control", autofocus: true %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :email %></br>
        </div>
        <div class = "col-md-8">
          <%= f.email_field :email , class: "form-control" %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= f.label :password %></br>
        </div>
        <div class = "col-md-8">
          <%= f.password_field :password , class: "form-control" %>
        </div>
      </div>
      
      <div class = "col-md-offset-2 col-md-2">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update User", class: "btn btn-success") %>
      </div>
    <% end %>
    <div class="col-md-2 ">
      <%= link_to "Go for Articles List", articles_path ,class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align:"center">Update User</h1>
<hr/>

<%= render 'form' %>

app/views/users/index.html.erb
<h2 align = "center">All Idea Bloggers</h2>

<div align="center">
  <%= will_paginate %>
</div>

<div align = "center">
    <div class = "row">
    <ul class = "listing">
      <% @users.each do |user| %>
        <div class = "well col-md-4 col-md-offset-4">
          
          
            <li><%= link_to gravatar_for(user,100), user_path(user) %></li>
            <li><%= link_to user.username ,user_path(user)%></li>
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "Delete user", user_path(user), :method => :delete, 
              :data => {:confirm => "Are you sure want to delete the User?"} %></li>
            <% end %>
            <li><small> <%= pluralize(user.articles.count,"article") if user.articles%></small></li>
          
        </div>
      <% end %>
    </ul>
  </div>
</div>

<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up New User</h1>
<hr/>

<%= render 'form' %>


  

app/views/users/show.html.erb
  <h3 class = "center">Wellcome <%= @user.username %></h3>
  <div class = "row">
    <div class = "co-md-4 center">
      <ul class = "listing">
        <li class = "article-title"><%= gravatar_for @user,150 %></li>
        <li><small><strong><%= @user.username %> have <%= pluralize(@user.articles.count, "article") if @user.articles%></strong></small></li>
      </ul>
    </div>
    
  </div>
  <div align="center">
    <%= will_paginate @user_articles %>
  </div>
  <%= render '/articles/articles' , obj: @user_articles %>
  <div align="center">
    <%= will_paginate @user_articles %>
  </div>